apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-pipeline-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/nginxinc/docker-nginx.git 
