apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-app-task-run
spec:
  serviceAccount: tekton-git-and-registry
  taskRef:
    name: build-app
  inputs:
    resources:
      - name: tekton-demo
        resourceRef:
          name: git-pipeline-resource
    params:
      - name: pathToDockerFile
        value: /workspace/tekton-demo/stable/alpine/Dockerfile
      - name: pathToContext
        value: /workspace/tekton-demo/stable/alpine
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: registry-pipelines-resource
